# Generated by Django 5.0.2 on 2024-04-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
    ]
